# Generated by Django 5.2.16 on 2026-07-18 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='General',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('basic_access', 'Kan de corp-hauling bekijken'), ('manage_settings', 'Kan de instellingen van Corp Hauling beheren')),
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corp_id', models.BigIntegerField(blank=True, help_text='De EVE corporation-id waarvan de contracten getoond worden. Laat leeg om de corp van het gekoppelde token te gebruiken.', null=True, verbose_name='Corporation-id')),
                ('corp_name', models.CharField(blank=True, default='', help_text='Wordt automatisch opgezocht bij opslaan; anders zelf invullen.', max_length=100, verbose_name='Corporation-naam')),
                ('kosten_model', models.CharField(choices=[('gates', 'Over gates — kosten per sprong'), ('jf', 'Jump freighter — brandstof per lichtjaar')], default='gates', help_text='Hoe de kosten van een contract berekend worden. Een jump freighter vliegt niet over gates maar springt op afstand, dus daar telt het aantal lichtjaren en de isotopen — niet het aantal sprongen.', max_length=10, verbose_name='Kostenmodel')),
                ('jf_bereik_ly', models.FloatField(default=10.0, help_text='Maximale sprongafstand van het schip. Een Ark/Anshar/Nomad/Rhea heeft 5,0 LY basis; met Jump Drive Calibration loopt dat op. Bepaalt alleen het gétoonde aantal sprongen, niet de brandstof.', verbose_name='Sprongbereik (lichtjaar)')),
                ('jf_isotopen_per_ly', models.FloatField(default=8800.0, help_text='Basisverbruik van het schip (uit EVE: 8.800 voor een jump freighter). Skills worden hieronder apart verrekend.', verbose_name='Isotopen per lichtjaar')),
                ('jf_brandstof_skill', models.PositiveSmallIntegerField(default=5, help_text='Elk niveau scheelt 10% brandstof. Op V betaal je dus de helft.', verbose_name='Jump Fuel Conservation (0-5)')),
                ('jf_isotoop_type_id', models.IntegerField(default=16274, help_text='Type-id van de brandstof: 16274 Helium (Amarr), 17887 Oxygen (Gallente), 17888 Nitrogen (Caldari), 17889 Hydrogen (Minmatar).', verbose_name='Isotoop-type')),
                ('jf_isotoop_prijs', models.FloatField(default=0, help_text='Vaste prijs per isotoop. Laat op 0 om automatisch de Jita-verkoopprijs te gebruiken.', verbose_name='Isotoopprijs (ISK, 0 = Jita)')),
                ('route_voorkeur', models.CharField(choices=[('kort', 'Kortste route — wat een piloot meestal vliegt'), ('veilig', 'Veilige route — highsec waar mogelijk')], default='kort', help_text="Met welke route de sprongen en kosten berekend worden. De piloot kiest zelf zijn route, dus standaard rekenen we met de kortste. Zet dit op 'veilig' als jullie highsec-only vliegen. Het aantal sprongen van de andere route wordt er altijd bij getoond.", max_length=10, verbose_name='Route om mee te rekenen')),
                ('isk_per_jump', models.BigIntegerField(default=20000000, help_text='Geschatte kosten per sprong voor de piloot (brandstof, tijd, slijtage). Netto winst = beloning − sprongen × dit bedrag. Richtwaarde: ~20.000.000 voor een freighter.', verbose_name='Kosten per sprong (ISK)')),
                ('min_reward', models.BigIntegerField(default=0, help_text='Contracten met een lagere beloning worden verborgen. 0 = alles tonen.', verbose_name='Minimale beloning (ISK)')),
                ('cache_minutes', models.PositiveSmallIntegerField(default=15, help_text='Hoe lang de contractenlijst uit ESI gecached wordt.', verbose_name='Verversen om de (minuten)')),
            ],
            options={
                'verbose_name': 'instellingen',
                'verbose_name_plural': 'instellingen',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Piloot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schip_type_id', models.IntegerField(choices=[(28850, 'Ark (Amarr)'), (28848, 'Anshar (Gallente)'), (28846, 'Nomad (Minmatar)'), (28844, 'Rhea (Caldari)')], default=28850, help_text='Bepaalt het isotopenverbruik, de brandstofsoort en hoeveel er in je hold past.', verbose_name='Schip')),
                ('skills_uit_esi', models.BooleanField(default=True, help_text='Leest Jump Drive Calibration en Jump Fuel Conservation van je character. Zet uit om ze hieronder zelf in te vullen.', verbose_name='Skills uit EVE halen')),
                ('jdc', models.PositiveSmallIntegerField(default=5, help_text='+20% sprongbereik per niveau (5,0 LY basis → 10,0 LY op V).', verbose_name='Jump Drive Calibration')),
                ('jfc', models.PositiveSmallIntegerField(default=5, help_text='−10% isotopenverbruik per niveau.', verbose_name='Jump Fuel Conservation')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='corphauling_piloot', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'piloot-profiel',
                'verbose_name_plural': 'piloot-profielen',
                'default_permissions': (),
            },
        ),
    ]
