# Generated by Django 5.2.16 on 2026-07-18 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corphauling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='piloot',
            name='fit',
            field=models.TextField(blank=True, default='', help_text='Plak hier je fit zoals je die in EVE kopieert. Modules die de vrachtruimte vergroten worden meegerekend, mét stacking-penalty. Laat leeg voor een kale romp.', verbose_name='Fit (plakken uit EVE)'),
        ),
        migrations.AddField(
            model_name='piloot',
            name='hold_handmatig',
            field=models.FloatField(default=0, help_text='Staat dit op 0, dan rekenen we de vrachtruimte uit op basis van je schip, skills en fit. Vul het getal uit de game in als je zeker wilt weten dat het klopt — dan gaat deze waarde voor.', verbose_name='Vrachtruimte zelf invullen (m³)'),
        ),
        migrations.AddField(
            model_name='piloot',
            name='jf_skill',
            field=models.PositiveSmallIntegerField(default=5, help_text='+10% vrachtruimte en −10% brandstof per niveau.', verbose_name='Jump Freighters'),
        ),
        migrations.AddField(
            model_name='piloot',
            name='rassen_skill',
            field=models.PositiveSmallIntegerField(default=5, help_text='Caldari/Gallente/Minmatar/Amarr Freighter: +5% vrachtruimte per niveau.', verbose_name='Freighter-skill van het ras'),
        ),
    ]
