# Generated by Django 5.2.16 on 2026-07-18 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corphauling', '0003_remove_piloot_fit_remove_piloot_hold_handmatig_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorpFit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(help_text='Zoals leden \'m in de keuzelijst zien, bijv. "Rhea — ORE".', max_length=80, verbose_name='Naam')),
                ('schip_type_id', models.IntegerField(choices=[(28850, 'Ark (Amarr)'), (28848, 'Anshar (Gallente)'), (28846, 'Nomad (Minmatar)'), (28844, 'Rhea (Caldari)')], help_text='Voor welk schip deze fit bedoeld is.', verbose_name='Schip')),
                ('fit', models.TextField(help_text='Het EFT-blok zoals je het uit EVE kopieert.', verbose_name='Fit')),
                ('volgorde', models.PositiveSmallIntegerField(default=0, help_text='Lager staat hoger in de lijst.', verbose_name='Volgorde')),
            ],
            options={
                'verbose_name': 'corp-fit',
                'verbose_name_plural': 'corp-fits',
                'ordering': ('volgorde', 'naam'),
                'default_permissions': (),
            },
        ),
    ]
