# Generated by Django 5.2.16 on 2026-07-18 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corphauling', '0004_corpfit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='piloot',
            name='jdc',
        ),
        migrations.RemoveField(
            model_name='piloot',
            name='jf_skill',
        ),
        migrations.RemoveField(
            model_name='piloot',
            name='jfc',
        ),
        migrations.RemoveField(
            model_name='piloot',
            name='rassen_skill',
        ),
        migrations.RemoveField(
            model_name='piloot',
            name='skills_uit_esi',
        ),
    ]
