# Generated by Django 5.2.16 on 2026-07-18 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corphauling', '0006_remove_schip_hold_handmatig_schip_corp_fit_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Config',
        ),
        migrations.RemoveField(
            model_name='schip',
            name='corp_fit',
        ),
        migrations.RemoveField(
            model_name='piloot',
            name='user',
        ),
        migrations.RemoveField(
            model_name='schip',
            name='piloot',
        ),
        migrations.AlterModelOptions(
            name='general',
            options={'default_permissions': (), 'managed': False, 'permissions': (('basic_access', 'Kan de haul-verdiensten bekijken'),)},
        ),
        migrations.DeleteModel(
            name='CorpFit',
        ),
        migrations.DeleteModel(
            name='Piloot',
        ),
        migrations.DeleteModel(
            name='Schip',
        ),
    ]
